"""make_en_name_nullable

Revision ID: 0addfb4429fe
Revises: add_video_en_name
Create Date: 2025-05-16 14:37:03.738833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0addfb4429fe'
down_revision = 'add_video_en_name'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('videos', 'en_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('videos', 'type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('web_configs', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='网页名称',
               existing_nullable=False)
    op.alter_column('web_configs', 'icon_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='图标URL',
               existing_nullable=True)
    op.alter_column('web_configs', 'video_carousel',
               existing_type=mysql.TINYINT(display_width=1),
               comment='视频是否轮播',
               existing_nullable=True)
    op.alter_column('web_configs', 'page_carousel',
               existing_type=mysql.TINYINT(display_width=1),
               comment='网页是否轮播',
               existing_nullable=True)
    op.alter_column('web_configs', 'current_carousel_page',
               existing_type=mysql.INTEGER(),
               comment='当前轮播页',
               existing_nullable=True)
    op.alter_column('web_configs', 'first_page_duration',
               existing_type=mysql.INTEGER(),
               comment='第一页停留时间(秒)',
               existing_nullable=True)
    op.alter_column('web_configs', 'second_page_duration',
               existing_type=mysql.INTEGER(),
               comment='第二页停留时间(秒)',
               existing_nullable=True)
    op.alter_column('web_configs', 'third_page_duration',
               existing_type=mysql.INTEGER(),
               comment='第三页停留时间(秒)',
               existing_nullable=True)
    op.alter_column('web_configs', 'visitor_count',
               existing_type=mysql.INTEGER(),
               comment='来访人数统计',
               existing_nullable=True)
    op.alter_column('web_configs', 'weekly_visitor_count',
               existing_type=mysql.INTEGER(),
               comment='本周访客数',
               existing_nullable=True)
    op.alter_column('web_configs', 'monthly_visitor_count',
               existing_type=mysql.INTEGER(),
               comment='本月访客数',
               existing_nullable=True)
    op.alter_column('web_configs', 'video_carousel_duration',
               existing_type=mysql.INTEGER(),
               comment='视频轮播停留时间(秒)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('web_configs', 'video_carousel_duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='视频轮播停留时间(秒)',
               existing_nullable=True)
    op.alter_column('web_configs', 'monthly_visitor_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='本月访客数',
               existing_nullable=True)
    op.alter_column('web_configs', 'weekly_visitor_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='本周访客数',
               existing_nullable=True)
    op.alter_column('web_configs', 'visitor_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='来访人数统计',
               existing_nullable=True)
    op.alter_column('web_configs', 'third_page_duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='第三页停留时间(秒)',
               existing_nullable=True)
    op.alter_column('web_configs', 'second_page_duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='第二页停留时间(秒)',
               existing_nullable=True)
    op.alter_column('web_configs', 'first_page_duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='第一页停留时间(秒)',
               existing_nullable=True)
    op.alter_column('web_configs', 'current_carousel_page',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='当前轮播页',
               existing_nullable=True)
    op.alter_column('web_configs', 'page_carousel',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='网页是否轮播',
               existing_nullable=True)
    op.alter_column('web_configs', 'video_carousel',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='视频是否轮播',
               existing_nullable=True)
    op.alter_column('web_configs', 'icon_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='图标URL',
               existing_nullable=True)
    op.alter_column('web_configs', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='网页名称',
               existing_nullable=False)
    op.alter_column('videos', 'type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('videos', 'en_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('videos', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ### 