"""add_company_award_association

Revision ID: 20e5c6dd78fd
Revises: 97e3b1bb3155
Create Date: 2025-04-25 17:32:06.306714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20e5c6dd78fd'
down_revision = '97e3b1bb3155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_award',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'award_id')
    )
    op.drop_constraint('companies_ibfk_1', 'companies', type_='foreignkey')
    op.drop_column('companies', 'award_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('award_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('companies_ibfk_1', 'companies', 'awards', ['award_id'], ['id'])
    op.drop_table('company_award')
    # ### end Alembic commands ### 