"""add_is_carousel_to_videos

Revision ID: 42296d435463
Revises: bad9381f2dfd
Create Date: 2024-04-29 12:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42296d435463'
down_revision = 'bad9381f2dfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_carousel', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'is_carousel')
    # ### end Alembic commands ### 