"""initial

Revision ID: 86014bd7429d
Revises: 
Create Date: 2025-04-25 15:19:54.113464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86014bd7429d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_carousel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_table('data_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_types_id'), 'data_types', ['id'], unique=False)
    op.create_table('training_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_fields_id'), 'training_fields', ['id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('carousel_add_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('visitor_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_records_id'), 'visitor_records', ['id'], unique=False)
    op.create_table('web_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('video_carousel', sa.Boolean(), nullable=True),
    sa.Column('page_carousel', sa.Boolean(), nullable=True),
    sa.Column('current_carousel_page', sa.Integer(), nullable=True),
    sa.Column('first_page_duration', sa.Integer(), nullable=True),
    sa.Column('second_page_duration', sa.Integer(), nullable=True),
    sa.Column('third_page_duration', sa.Integer(), nullable=True),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_configs_id'), 'web_configs', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.Column('is_carousel', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('industry_type', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('create_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('product_location', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('training_field_id', sa.Integer(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('is_carousel', sa.Boolean(), nullable=True),
    sa.Column('carousel_add_time', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['training_field_id'], ['training_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_robots_id'), 'robots', ['id'], unique=False)
    op.create_table('data_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type_id', sa.Integer(), nullable=True),
    sa.Column('collect_date', sa.String(length=50), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_type_id'], ['data_types.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_records_id'), 'data_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_records_id'), table_name='data_records')
    op.drop_table('data_records')
    op.drop_index(op.f('ix_robots_id'), table_name='robots')
    op.drop_table('robots')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_web_configs_id'), table_name='web_configs')
    op.drop_table('web_configs')
    op.drop_index(op.f('ix_visitor_records_id'), table_name='visitor_records')
    op.drop_table('visitor_records')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_training_fields_id'), table_name='training_fields')
    op.drop_table('training_fields')
    op.drop_index(op.f('ix_data_types_id'), table_name='data_types')
    op.drop_table('data_types')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ### 