"""change_robot_award_to_string

Revision ID: 97e3b1bb3155
Revises: 86014bd7429d
Create Date: 2025-04-25 16:31:29.842479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97e3b1bb3155'
down_revision = '86014bd7429d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('awards', sa.String(length=500), nullable=True))
    op.alter_column('robots', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('robots', 'industry_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('robots', 'skills',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('robots', 'recommendation_reason',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('serial_number', table_name='robots')
    op.drop_constraint('robots_ibfk_1', 'robots', type_='foreignkey')
    op.drop_column('robots', 'award_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('award_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('robots_ibfk_1', 'robots', 'awards', ['award_id'], ['id'])
    op.create_index('serial_number', 'robots', ['serial_number'], unique=True)
    op.alter_column('robots', 'recommendation_reason',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('robots', 'skills',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('robots', 'industry_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('robots', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('robots', 'awards')
    # ### end Alembic commands ### 