"""update_database_schema

Revision ID: 9c6e5d4c27f4
Revises: 
Create Date: 2025-04-07 00:25:09.059625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c6e5d4c27f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('data_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_types_id'), 'data_types', ['id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('visitor_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_records_id'), 'visitor_records', ['id'], unique=False)
    op.create_table('web_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_web_configs_id'), 'web_configs', ['id'], unique=False)
    op.create_table('data_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('collect_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_type_id'], ['data_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_records_id'), 'data_records', ['id'], unique=False)
    op.drop_index('ix_award_records_id', table_name='award_records')
    op.drop_table('award_records')
    op.drop_index('ix_robot_types_id', table_name='robot_types')
    op.drop_table('robot_types')
    op.drop_index('ix_participation_records_id', table_name='participation_records')
    op.drop_table('participation_records')
    op.drop_index('ix_task_records_id', table_name='task_records')
    op.drop_table('task_records')
    op.drop_index('ix_training_records_id', table_name='training_records')
    op.drop_table('training_records')
    op.drop_index('ix_display_videos_id', table_name='display_videos')
    op.drop_table('display_videos')
    op.drop_index('ix_entry_records_id', table_name='entry_records')
    op.drop_table('entry_records')
    op.add_column('robots', sa.Column('robot_type', sa.String(length=50), nullable=False))
    op.add_column('robots', sa.Column('industry_type', sa.String(length=50), nullable=False))
    op.add_column('robots', sa.Column('product_series', sa.String(length=50), nullable=True))
    op.add_column('robots', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('robots', sa.Column('training_status', sa.String(length=50), nullable=True))
    op.add_column('robots', sa.Column('awards', sa.Text(), nullable=True))
    op.add_column('robots', sa.Column('product_location', sa.String(length=100), nullable=True))
    op.add_column('robots', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('robots', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('robots', 'skills',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('robots', 'dimensions',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('robots', 'remarks',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'robots', ['serial_number'])
    op.drop_column('robots', 'body_type')
    op.drop_column('robots', 'origin')
    op.drop_column('robots', 'honors')
    op.drop_column('robots', 'parameters')
    op.drop_column('robots', 'weight')
    op.drop_column('robots', 'brand')
    op.add_column('training_fields', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('training_fields', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.alter_column('training_fields', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('training_fields', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('training_fields', 'scene_image_url')
    op.drop_column('training_fields', 'monitor_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_fields', sa.Column('monitor_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('training_fields', sa.Column('scene_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('training_fields', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('training_fields', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('training_fields', 'create_time')
    op.drop_column('training_fields', 'image_url')
    op.add_column('robots', sa.Column('brand', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('robots', sa.Column('weight', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('robots', sa.Column('parameters', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('robots', sa.Column('honors', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('robots', sa.Column('origin', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('robots', sa.Column('body_type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'robots', type_='unique')
    op.alter_column('robots', 'remarks',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('robots', 'dimensions',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('robots', 'skills',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('robots', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('robots', 'is_active')
    op.drop_column('robots', 'product_location')
    op.drop_column('robots', 'awards')
    op.drop_column('robots', 'training_status')
    op.drop_column('robots', 'status')
    op.drop_column('robots', 'product_series')
    op.drop_column('robots', 'industry_type')
    op.drop_column('robots', 'robot_type')
    op.create_table('entry_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('robot_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], name='entry_records_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_entry_records_id', 'entry_records', ['id'], unique=False)
    op.create_table('display_videos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_display_videos_id', 'display_videos', ['id'], unique=False)
    op.create_table('training_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('robot_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('online', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offline', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fault', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['training_fields.id'], name='training_records_ibfk_2'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], name='training_records_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_training_records_id', 'training_records', ['id'], unique=False)
    op.create_table('task_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('robot_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('task_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('completion_rate', mysql.FLOAT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_task_records_id', 'task_records', ['id'], unique=False)
    op.create_table('participation_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visitor_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_participation_records_id', 'participation_records', ['id'], unique=False)
    op.create_table('robot_types',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_robot_types_id', 'robot_types', ['id'], unique=False)
    op.create_table('award_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('award_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('award_level', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('issuing_authority', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('award_date', mysql.DATETIME(), nullable=False),
    sa.Column('certificate_image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('award_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('robot_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(((`robot_id` is not null) or (`field_id` is not null)) and ((`robot_id` is null) or (`field_id` is null)))', name='check_award_target'),
    sa.ForeignKeyConstraint(['field_id'], ['training_fields.id'], name='award_records_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], name='award_records_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_award_records_id', 'award_records', ['id'], unique=False)
    op.drop_index(op.f('ix_data_records_id'), table_name='data_records')
    op.drop_table('data_records')
    op.drop_index(op.f('ix_web_configs_id'), table_name='web_configs')
    op.drop_table('web_configs')
    op.drop_index(op.f('ix_visitor_records_id'), table_name='visitor_records')
    op.drop_table('visitor_records')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_data_types_id'), table_name='data_types')
    op.drop_table('data_types')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ### 