"""add_video_en_name

Revision ID: add_video_en_name
Revises: cd94b61170a8
Create Date: 2024-04-29 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_video_en_name'
down_revision = 'cd94b61170a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('en_name', sa.String(length=100), nullable=True))
    
    # 为现有记录生成默认的en_name
    op.execute("UPDATE videos SET en_name = CONCAT('camera_', id) WHERE en_name IS NULL")
    
    # 将en_name设置为非空并添加唯一索引
    op.alter_column('videos', 'en_name',
               existing_type=sa.String(length=100),
               nullable=False)
    op.create_unique_constraint('uq_videos_en_name', 'videos', ['en_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_videos_en_name', 'videos', type_='unique')
    op.drop_column('videos', 'en_name')
    # ### end Alembic commands ### 