"""add_create_time_to_videos

Revision ID: bad9381f2dfd
Revises: 20e5c6dd78fd
Create Date: 2024-04-29 12:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad9381f2dfd'
down_revision = '20e5c6dd78fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('create_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'create_time')
    # ### end Alembic commands ### 