"""fix_video_fields

Revision ID: fix_video_fields
Revises: add_missing_video_fields
Create Date: 2024-04-29 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'fix_video_fields'
down_revision = 'add_missing_video_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('videos')]
    
    # 添加缺失的字段
    if 'type' not in columns:
        op.add_column('videos', sa.Column('type', sa.String(length=20), nullable=True))
    
    if 'carousel_add_time' not in columns:
        op.add_column('videos', sa.Column('carousel_add_time', sa.String(length=50), nullable=True))
    
    # 删除不需要的字段
    if 'image_url' in columns:
        op.drop_column('videos', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('videos')]
    
    # 恢复删除的字段
    if 'image_url' not in columns:
        op.add_column('videos', sa.Column('image_url', sa.String(length=255), nullable=True))
    
    # 删除新添加的字段
    if 'type' in columns:
        op.drop_column('videos', 'type')
    
    if 'carousel_add_time' in columns:
        op.drop_column('videos', 'carousel_add_time')
    # ### end Alembic commands ### 