"""remove_video_url

Revision ID: remove_video_url
Revises: fix_video_fields
Create Date: 2024-04-29 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'remove_video_url'
down_revision = 'fix_video_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('videos')]
    
    # 删除不需要的字段
    if 'video_url' in columns:
        op.drop_column('videos', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('videos')]
    
    # 恢复删除的字段
    if 'video_url' not in columns:
        op.add_column('videos', sa.Column('video_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ### 